#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 6379

#logging.level.org.springframework.web.reactive: DEBUG
logging.level.com.nosbielc: DEBUG
inventory:
  uri: "https://www.random.org"
  endpoint: "/integers/?num=1&min=0&max=20&col=1&base=10&format=plain"